
// This file was auto-generated by ML.NET Model Builder. 

using PredictiveMaintenanceConsole;

// Create single instance of sample data from first line of dataset for model input
PredictiveMaintenanceModel.ModelInput sampleData = new PredictiveMaintenanceModel.ModelInput()
{
    Product_ID = @"L47181",
    Type = @"L",
    Air_temperature = 2982F,
    Process_temperature = 3087F,
    Rotational_speed = 1408F,
    Torque = 463F,
    Tool_wear = 3F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Machine_failure with predicted Machine_failure from sample data...\n\n");


Console.WriteLine($"Product_ID: {@"L47181"}");
Console.WriteLine($"Type: {@"L"}");
Console.WriteLine($"Air_temperature: {2982F}");
Console.WriteLine($"Process_temperature: {3087F}");
Console.WriteLine($"Rotational_speed: {1408F}");
Console.WriteLine($"Torque: {463F}");
Console.WriteLine($"Tool_wear: {3F}");
Console.WriteLine($"Machine_failure: {0F}");


var sortedScoresWithLabel = PredictiveMaintenanceModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

